
SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS order_book;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS press;
DROP TABLE IF EXISTS vip_rate;

SET FOREIGN_KEY_CHECKS = 1;